### ISSUE TITLE
City not growing with new update

### ISSUE THREAD

**Issue by Edou24** [Infixo/CS2-RealEco#2]
After playing a little bit after the new update of the mod i realised my city was decreasing in population even tho my demand was high and after uninstalling the mod my city started increasing in population again. pls fix i really like your mod.

**Comment by Edou24** [comment]
and also for some reason with the mod realistic density it stopped workers from acessing jobs in the car factory

**Comment by Infixo** [comment]
1. Realistic Density does not work well with Economy rebalance, sorry. You should not use both mods as of now.
2. Any population changes are not related to Economy Rebalance. Sorry, but the mod has nothing to do with population. You probably observe a result of other mods, maybe a conflict, etc. this game is really complex, so many things may cause such effects.

**Comment by Edou24** [comment]
ok thanks
