### ISSUE TITLE
Game won't start when Economy Rebalance is enable. 

### ISSUE THREAD

**Issue by TMcleod21** [Infixo/CS2-RealEco#3]
[Message:   BepInEx] BepInEx 5.4.21.0 - Cities2 (3/3/2024 4:32:23 AM)
[Info   :   BepInEx] Running under Unity v2022.3.7.9732149
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 7 plugins to load
[Info   :   BepInEx] Loading [Better Bulldozer 1.0.2]
[Info   :   Console] Logs at C:/Users/mcleo/AppData/LocalLow/Colossal Order/Cities Skylines II/Logs
[Info   :   BepInEx] Loading [Cities2Mods.CityPlayerServiceVehicleAI 0.4.1]
[Info   :Cities2Mods.CityPlayerServiceVehicleAI] Cities2Mods.CityPlayerServiceVehicleAI_0.4.1_by CityPlayer
[Info   :Cities2Mods.CityPlayerServiceVehicleAI] Discord link: https://discord.gg/RyBRtyuMQw
[Info   :   BepInEx] Loading [Unified Icon Library 1.0.7]
[Info   :   BepInEx] Loading [LandValueOverhaul 1.4.3]
[Info   :LandValueOverhaul] LandValueOverhaul v1.4.3 is loaded!
[Info   :   BepInEx] Loading [RealEco 0.5.0]
[Info   :   RealEco] Plugin RealEco is loaded!
[Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly RealEco, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
System.IO.FileNotFoundException: Could not load file or assembly 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'
[Info   :   RealEco] Plugin RealEco made patches! Patched methods: 13
[Info   :   RealEco] Patched method: Game.dll:Initialize
[Info   :   RealEco] Patched method: Game.dll:OnCreate
[Info   :   RealEco] Patched method: Game.dll:OnDestroy
[Info   :   RealEco] Patched method: Game.dll:OnUpdate
[Info   :   RealEco] Patched method: Game.dll:OnCreateForCompiler
[Info   :   RealEco] Patched method: Game.dll:UpdateZoneInfo
[Info   :   RealEco] Patched method: Game.dll:UpdateStorageInfo
[Info   :   RealEco] Patched method: Game.dll:PrintCompanyDebug
[Info   :   RealEco] Patched method: Game.dll:OnUpdate
[Info   :   RealEco] Patched method: Game.dll:OnUpdate
[Info   :   RealEco] Patched method: Game.dll:AddPrefab
[Info   :   RealEco] Patched method: Game.dll:AddPrefabsTo
[Info   :   RealEco] Patched method: Game.dll:OnUpdate
[Info   :   BepInEx] Loading [Tree Controller 1.1.4]
[Info   :   BepInEx] Loading [Abandoned Building Remover 0.0.1]
[Info   :Abandoned Building Remover] Plugin AbandonedBuildingRemover 0.0.1 is loaded! Patched methods: 1
[Info   :Abandoned Building Remover] Patched method: Game.dll:OnCreate
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
System.Reflection.Assembly.GetTypes () (at <b89873cb176e44a995a4781c7487d410>:0)
Unity.Entities.TypeManager.InitializeAllComponentTypes () (at <39f0c89f34b343ec87d653ea70eaa86b>:0)
Unity.Entities.TypeManager.Initialize () (at <39f0c89f34b343ec87d653ea70eaa86b>:0)
Unity.Entities.AttachToEntityClonerInjection.Initialize () (at <3e90123a5a384545901b580ab411bafb>:0)
Unity.Entities.AttachToEntityClonerInjection..cctor () (at <3e90123a5a384545901b580ab411bafb>:0)
Rethrow as TypeInitializationException: The type initializer for 'Unity.Entities.AttachToEntityClonerInjection' threw an exception.
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[Info   : Unity Log] Game version: 1.0.19f1 (3900.25596) [5348.29428]
[Info   : Unity Log] Type: Desktop
OS: Windows 11  (10.0.22631) 64bit
System memory: 31.931 GB
Graphics device: NVIDIA GeForce RTX 3080 (Version: Direct3D 11.0 [level 11.1])
Graphics memory: 9.817 GB
Max texture size: 16384
Shader level: 50
3D textures: True
Shadows: True
Compute: True
CPU: AMD Ryzen 5 5600X 6-Core Processor 
Core count: 12
Platform: WindowsPlayer
Screen resolution: 1920x1080x239
Window resolution: 1920x1080
DPI: 96
Rendering Threading Mode: LegacyJobified
CLR: 4.0.30319.42000
Modding runtime: BepInEx 5.4.21.0
Scripting runtime: Mono 6.13.0 (Visual Studio built mono)
[Error  : Unity Log] [SceneFlow] [FATAL]  Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 
  at Unity.Entities.TypeManager.InitializeAllComponentTypes () [0x00044] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Unity.Entities.TypeManager.Initialize () [0x001c0] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Unity.Entities.EntityManager.Initialize (Unity.Entities.World world) [0x00000] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Unity.Entities.WorldUnmanaged.Create (Unity.Entities.World world, Unity.Entities.WorldFlags flags, Unity.Collections.AllocatorManager+AllocatorHandle backingAllocatorHandle) [0x0006d] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Unity.Entities.World.Init (Unity.Entities.WorldFlags flags, Unity.Collections.AllocatorManager+AllocatorHandle backingAllocatorHandle) [0x00000] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Unity.Entities.World..ctor (System.String name, Unity.Entities.WorldFlags flags) [0x00044] in <39f0c89f34b343ec87d653ea70eaa86b>:0 
  at Game.SceneFlow.GameManager.CreateWorld () [0x00027] in <8bc3bf147d90443fb3df643f5b67c57a>:0 
  at Game.SceneFlow.GameManager.Initialize () [0x001c5] in <8bc3bf147d90443fb3df643f5b67c57a>:0 
System.TypeLoadException: Could not load file or assembly 'HookUILib, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
[Info   : Unity Log] Game terminated successfully

**Comment by Infixo** [comment]
You need to install HookUI v0.3.9 because there is a UI window now in the mod. Sorry, I forgot to add the dependency link.
https://thunderstore.io/c/cities-skylines-ii/p/Cities2Modding/HookUI/

**Comment by TMcleod21** [comment]
Thank you so much, everything working. Have a wonderful day!. Fix!
